CREATE TABLE venues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    country VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    address TEXT NOT NULL
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    venue_id BIGINT NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL,

    CONSTRAINT events_time_check
        CHECK (end_time > start_time),

    CONSTRAINT events_status_check CHECK (
        status IN ('DRAFT', 'PUBLISHED', 'CANCELLED')
    ),

    FOREIGN KEY (venue_id) REFERENCES venues(id)
);

CREATE TABLE seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    seat_row TEXT NOT NULL,
    seat_number INT NOT NULL,

    CONSTRAINT seats_event_position_unique
        UNIQUE (event_id, seat_row, seat_number),

    CONSTRAINT seats_number_check
        CHECK (seat_number > 0),

    FOREIGN KEY (event_id) REFERENCES events(id)
);